In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
hr=120*"-"

In [3]:
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2.,'Hello'),(2,3.,"World")]
recarr[:] = toadd

recarr

array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [6]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
# Now creating the columns we want to put
# in the recarray
col1 = np.arange(2) + 1
col2 = np.arange(2, dtype=np.float32)
col3 = ['Hello', 'World']
# Here we create a list of tuples that is
# identical to the previous toadd list.
toadd = zip(col1, col2, col3)
# Assigning values to recarr
recarr[:] = toadd
# Assigning names to each column, which
# are now by default called 'f0', 'f1', and 'f2'.
recarr.dtype.names = ('Integers' , 'Floats', 'Strings')
# If we want to access one of the columns by its name, we
# can do the following.
toadd,hr,recarr['Integers']
# array([1, 2], dtype=int32)

([(1, 0.0, 'Hello'), (2, 1.0, 'World')],
 '------------------------------------------------------------------------------------------------------------------------',
 array([1, 2], dtype=int32))

In [7]:
alist=[[1,2],[3,4]]
# Converting the list defined above into an array
arr = np.array(alist)
# To return the (0,1) element we use ...
arr[0,1]
# Now to access the last column, we simply use ...
arr[:,1]
# Accessing the columns is achieved in the same way,
# which is the bottom row.
arr[1,:]


array([3, 4])

In [8]:
# Creating an array
arr = np.arange(5)
# Creating the index array
index = np.where(arr > 2)

# Creating the desired array
new_arr = arr[index]
new_arr = np.delete(arr, index)
index = arr > 2

new_arr = arr[index]

index,hr,new_arr

(array([False, False, False,  True,  True], dtype=bool),
 '------------------------------------------------------------------------------------------------------------------------',
 array([3, 4]))